# vim:ft=dockerfile

FROM node:20-bullseye-slim

RUN mkdir /app && chown -R node:node /app
WORKDIR /app
USER node

COPY --chown=node:node package.json package-lock.json . 

RUN npm ci --omit=dev && npm cache clean --force

COPY --chown=node:node apps/api packages /app

RUN cat package-lock.json && npm run build:api

EXPOSE 5000
CMD ["npm", "run", "start:api"]
