-- Create the comments table in your Neon database
-- Run this SQL in the Neon SQL Editor (without EXPLAIN)

-- Option 1: Using BIGSERIAL (recommended)
CREATE TABLE IF NOT EXISTS comments (
  id BIGSERIAL PRIMARY KEY,
  comment TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Option 2: Using modern IDENTITY syntax (if Option 1 doesn't work)
-- CREATE TABLE IF NOT EXISTS comments (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   comment TEXT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Option 3: Using INTEGER with explicit sequence (if both above don't work)
-- CREATE SEQUENCE IF NOT EXISTS comments_id_seq;
-- CREATE TABLE IF NOT EXISTS comments (
--   id INTEGER PRIMARY KEY DEFAULT nextval('comments_id_seq'),
--   comment TEXT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

